/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_isolated_nodes' is deprecated, use 'has_isolated_nodes' instead
  warnings.warn(out)
/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  warnings.warn(out)
[codecarbon INFO @ 10:56:15] offline tracker init
[codecarbon ERROR @ 10:56:15] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:56:15] [setup] RAM Tracking...
[codecarbon INFO @ 10:56:15] [setup] GPU Tracking...
[codecarbon INFO @ 10:56:15] No GPU found.
[codecarbon INFO @ 10:56:15] [setup] CPU Tracking...
[codecarbon INFO @ 10:56:15] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:56:15] >>> Tracker's metadata:
[codecarbon INFO @ 10:56:15]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:56:15]   Python version: 3.9.13
[codecarbon INFO @ 10:56:15]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:56:15]   CPU count: 1
[codecarbon INFO @ 10:56:15]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:56:15]   GPU count: None
[codecarbon INFO @ 10:56:15]   GPU model: None
[codecarbon WARNING @ 10:56:15] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:56:15] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:56:15] stopping.
[codecarbon INFO @ 10:56:29] Energy consumed for RAM : 0.000015 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:56:29] Energy consumed for all CPUs : 0.000671 kWh. All CPUs Power : 169.90446491254093 W
[codecarbon INFO @ 10:56:29] 0.000686 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:56:29] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:56:29] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:56:29] stopping.
[codecarbon INFO @ 10:56:54] offline tracker init
[codecarbon ERROR @ 10:56:54] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:56:55] [setup] RAM Tracking...
[codecarbon INFO @ 10:56:55] [setup] GPU Tracking...
[codecarbon INFO @ 10:56:55] No GPU found.
[codecarbon INFO @ 10:56:55] [setup] CPU Tracking...
[codecarbon INFO @ 10:56:55] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:56:55] >>> Tracker's metadata:
[codecarbon INFO @ 10:56:55]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:56:55]   Python version: 3.9.13
[codecarbon INFO @ 10:56:55]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:56:55]   CPU count: 1
[codecarbon INFO @ 10:56:55]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:56:55]   GPU count: None
[codecarbon INFO @ 10:56:55]   GPU model: None
[codecarbon WARNING @ 10:56:55] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:56:55] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:56:55] stopping.
[codecarbon INFO @ 10:57:10] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:57:11] Energy consumed for all CPUs : 0.000740 kWh. All CPUs Power : 170.3018729139419 W
[codecarbon INFO @ 10:57:11] 0.000756 kWh of electricity used since the begining.
[codecarbon INFO @ 10:57:14] Energy consumed for RAM : 0.000019 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:57:14] Energy consumed for all CPUs : 0.000889 kWh. All CPUs Power : 170.80346819839534 W
[codecarbon INFO @ 10:57:14] 0.000907 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:57:14] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:57:14] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:57:14] stopping.
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
/home/cdonnat/.local/lib/python3.9/site-packages/sklearn/multiclass.py:77: UserWarning: Label not 6 is present in all training examples.
  warnings.warn(
[codecarbon INFO @ 10:57:28] offline tracker init
[codecarbon ERROR @ 10:57:28] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:57:28] [setup] RAM Tracking...
[codecarbon INFO @ 10:57:28] [setup] GPU Tracking...
[codecarbon INFO @ 10:57:28] No GPU found.
[codecarbon INFO @ 10:57:28] [setup] CPU Tracking...
[codecarbon INFO @ 10:57:28] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:57:28] >>> Tracker's metadata:
[codecarbon INFO @ 10:57:28]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:57:28]   Python version: 3.9.13
[codecarbon INFO @ 10:57:28]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:57:28]   CPU count: 1
[codecarbon INFO @ 10:57:28]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:57:28]   GPU count: None
[codecarbon INFO @ 10:57:28]   GPU model: None
[codecarbon WARNING @ 10:57:28] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:57:28] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:57:28] stopping.
[codecarbon INFO @ 10:57:44] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:57:44] Energy consumed for all CPUs : 0.000743 kWh. All CPUs Power : 170.37182243069378 W
[codecarbon INFO @ 10:57:44] 0.000758 kWh of electricity used since the begining.
[codecarbon INFO @ 10:57:49] Energy consumed for RAM : 0.000020 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:57:49] Energy consumed for all CPUs : 0.000962 kWh. All CPUs Power : 170.84287946518862 W
[codecarbon INFO @ 10:57:49] 0.000982 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:57:49] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:57:49] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:57:49] stopping.
[codecarbon INFO @ 10:58:05] offline tracker init
[codecarbon ERROR @ 10:58:05] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:58:05] [setup] RAM Tracking...
[codecarbon INFO @ 10:58:05] [setup] GPU Tracking...
[codecarbon INFO @ 10:58:05] No GPU found.
[codecarbon INFO @ 10:58:05] [setup] CPU Tracking...
[codecarbon INFO @ 10:58:05] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:58:05] >>> Tracker's metadata:
[codecarbon INFO @ 10:58:05]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:58:05]   Python version: 3.9.13
[codecarbon INFO @ 10:58:05]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:58:05]   CPU count: 1
[codecarbon INFO @ 10:58:05]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:58:05]   GPU count: None
[codecarbon INFO @ 10:58:05]   GPU model: None
[codecarbon WARNING @ 10:58:05] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:58:05] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:58:05] stopping.
[codecarbon INFO @ 10:58:21] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:58:21] Energy consumed for all CPUs : 0.000739 kWh. All CPUs Power : 169.73069301112506 W
[codecarbon INFO @ 10:58:21] 0.000755 kWh of electricity used since the begining.
[codecarbon INFO @ 10:58:36] Energy consumed for RAM : 0.000031 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:58:36] Energy consumed for all CPUs : 0.001449 kWh. All CPUs Power : 170.35576637303933 W
[codecarbon INFO @ 10:58:36] 0.001479 kWh of electricity used since the begining.
[codecarbon INFO @ 10:58:49] Energy consumed for RAM : 0.000045 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:58:50] Energy consumed for all CPUs : 0.002096 kWh. All CPUs Power : 170.50705936753758 W
[codecarbon INFO @ 10:58:50] 0.002141 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:58:50] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:58:50] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:58:50] stopping.
[codecarbon INFO @ 10:59:08] offline tracker init
[codecarbon ERROR @ 10:59:08] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:59:08] [setup] RAM Tracking...
[codecarbon INFO @ 10:59:08] [setup] GPU Tracking...
[codecarbon INFO @ 10:59:08] No GPU found.
[codecarbon INFO @ 10:59:08] [setup] CPU Tracking...
[codecarbon INFO @ 10:59:08] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:59:08] >>> Tracker's metadata:
[codecarbon INFO @ 10:59:08]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:59:08]   Python version: 3.9.13
[codecarbon INFO @ 10:59:08]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:59:08]   CPU count: 1
[codecarbon INFO @ 10:59:08]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:59:08]   GPU count: None
[codecarbon INFO @ 10:59:08]   GPU model: None
[codecarbon WARNING @ 10:59:08] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:59:08] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:59:08] stopping.
[codecarbon INFO @ 10:59:24] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:59:24] Energy consumed for all CPUs : 0.000739 kWh. All CPUs Power : 169.78996745145903 W
[codecarbon INFO @ 10:59:24] 0.000755 kWh of electricity used since the begining.
[codecarbon INFO @ 10:59:39] Energy consumed for RAM : 0.000031 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:59:39] Energy consumed for all CPUs : 0.001447 kWh. All CPUs Power : 170.78544111606772 W
[codecarbon INFO @ 10:59:39] 0.001478 kWh of electricity used since the begining.
[codecarbon INFO @ 10:59:54] Energy consumed for RAM : 0.000046 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:59:54] Energy consumed for all CPUs : 0.002161 kWh. All CPUs Power : 170.68826012854277 W
[codecarbon INFO @ 10:59:54] 0.002207 kWh of electricity used since the begining.
[codecarbon INFO @ 11:00:09] Energy consumed for RAM : 0.000061 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:00:09] Energy consumed for all CPUs : 0.002872 kWh. All CPUs Power : 170.57966628589446 W
[codecarbon INFO @ 11:00:09] 0.002932 kWh of electricity used since the begining.
[codecarbon INFO @ 11:00:24] Energy consumed for RAM : 0.000075 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:00:24] Energy consumed for all CPUs : 0.003584 kWh. All CPUs Power : 170.75261325980324 W
[codecarbon INFO @ 11:00:24] 0.003659 kWh of electricity used since the begining.
[codecarbon INFO @ 11:00:39] Energy consumed for RAM : 0.000090 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:00:39] Energy consumed for all CPUs : 0.004293 kWh. All CPUs Power : 170.69723235848534 W
[codecarbon INFO @ 11:00:39] 0.004384 kWh of electricity used since the begining.
[codecarbon INFO @ 11:00:53] Energy consumed for RAM : 0.000105 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:00:53] Energy consumed for all CPUs : 0.004959 kWh. All CPUs Power : 170.6556766117779 W
[codecarbon INFO @ 11:00:53] 0.005064 kWh of electricity used since the begining.
[codecarbon WARNING @ 11:00:53] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:00:53] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 11:00:53] stopping.
[codecarbon INFO @ 11:01:20] offline tracker init
[codecarbon ERROR @ 11:01:20] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 11:01:20] [setup] RAM Tracking...
[codecarbon INFO @ 11:01:20] [setup] GPU Tracking...
[codecarbon INFO @ 11:01:20] No GPU found.
[codecarbon INFO @ 11:01:20] [setup] CPU Tracking...
[codecarbon INFO @ 11:01:20] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 11:01:21] >>> Tracker's metadata:
[codecarbon INFO @ 11:01:21]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 11:01:21]   Python version: 3.9.13
[codecarbon INFO @ 11:01:21]   Available RAM : 10.000 GB
[codecarbon INFO @ 11:01:21]   CPU count: 1
[codecarbon INFO @ 11:01:21]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 11:01:21]   GPU count: None
[codecarbon INFO @ 11:01:21]   GPU model: None
[codecarbon WARNING @ 11:01:21] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:01:21] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 11:01:21] stopping.
[codecarbon INFO @ 11:01:36] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:01:36] Energy consumed for all CPUs : 0.000745 kWh. All CPUs Power : 171.008007208435 W
[codecarbon INFO @ 11:01:36] 0.000760 kWh of electricity used since the begining.
[codecarbon INFO @ 11:01:51] Energy consumed for RAM : 0.000031 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:01:51] Energy consumed for all CPUs : 0.001455 kWh. All CPUs Power : 169.83496243392798 W
[codecarbon INFO @ 11:01:51] 0.001485 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:06] Energy consumed for RAM : 0.000045 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:06] Energy consumed for all CPUs : 0.002165 kWh. All CPUs Power : 171.1344821506445 W
[codecarbon INFO @ 11:02:06] 0.002211 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:21] Energy consumed for RAM : 0.000060 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:21] Energy consumed for all CPUs : 0.002876 kWh. All CPUs Power : 171.34648036458242 W
[codecarbon INFO @ 11:02:21] 0.002937 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:36] Energy consumed for RAM : 0.000075 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:36] Energy consumed for all CPUs : 0.003591 kWh. All CPUs Power : 171.24563318052134 W
[codecarbon INFO @ 11:02:36] 0.003666 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:51] Energy consumed for RAM : 0.000090 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:51] Energy consumed for all CPUs : 0.004306 kWh. All CPUs Power : 171.28238542013642 W
[codecarbon INFO @ 11:02:51] 0.004397 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:06] Energy consumed for RAM : 0.000105 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:06] Energy consumed for all CPUs : 0.005020 kWh. All CPUs Power : 171.32864044145433 W
[codecarbon INFO @ 11:03:06] 0.005125 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:21] Energy consumed for RAM : 0.000120 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:21] Energy consumed for all CPUs : 0.005735 kWh. All CPUs Power : 171.501276041319 W
[codecarbon INFO @ 11:03:21] 0.005855 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:36] Energy consumed for RAM : 0.000135 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:36] Energy consumed for all CPUs : 0.006445 kWh. All CPUs Power : 171.2529050303804 W
[codecarbon INFO @ 11:03:36] 0.006580 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:51] Energy consumed for RAM : 0.000150 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:51] Energy consumed for all CPUs : 0.007163 kWh. All CPUs Power : 171.28476705996098 W
[codecarbon INFO @ 11:03:51] 0.007313 kWh of electricity used since the begining.
[codecarbon INFO @ 11:04:06] Energy consumed for RAM : 0.000165 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:04:06] Energy consumed for all CPUs : 0.007877 kWh. All CPUs Power : 171.28602794915196 W
[codecarbon INFO @ 11:04:06] 0.008042 kWh of electricity used since the begining.
[codecarbon INFO @ 11:04:21] Energy consumed for RAM : 0.000180 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:04:21] Energy consumed for all CPUs : 0.008588 kWh. All CPUs Power : 171.29511460351796 W
[codecarbon INFO @ 11:04:21] 0.008768 kWh of electricity used since the begining.
